// Base: eslint-config-next (official, generated by create-next-app - registers
// @next/eslint-plugin-next, eslint-plugin-react, eslint-plugin-react-hooks,
// eslint-plugin-jsx-a11y, eslint-plugin-import, typescript-eslint).
// Layered on top: the repository standard from .claude/presets/node-typescript
// (stricter type-checked rules, complexity/naming/layering rules, plugins Next does not
// ship: unicorn, sonarjs, security, unused-imports, eslint-comments, testing-library).
//
// This file itself is not part of the app's tsconfig program (config files aren't -
// see parserOptions.projectService.allowDefaultProject below), so it is linted under a
// default, non-type-checked project. That is why the "config files" block near the
// bottom turns the type-aware `no-unsafe-*` rules back off for `*.config.*` - there is
// no real type information available to make them meaningful here.

import { defineConfig, globalIgnores } from "eslint/config";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";
import typescriptEslint from "typescript-eslint";
import unicorn from "eslint-plugin-unicorn";
import sonarjs from "eslint-plugin-sonarjs";
import security from "eslint-plugin-security";
import unusedImports from "eslint-plugin-unused-imports";
import eslintComments from "@eslint-community/eslint-plugin-eslint-comments/configs";
import testingLibrary from "eslint-plugin-testing-library";
import jsonPlugin from "@eslint/json";
import prettierConfig from "eslint-config-prettier";

export default defineConfig([
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "dist/**",
    "coverage/**",
    "src/generated/**",
    "e2e/.results/**",
    "playwright-report/**",
    "**/*.generated.ts",
    // Reference templates for other stacks (vue/svelte/python/...) and shared snippets -
    // not part of this app, never meant to be linted as if they were.
    ".claude/**",
    // Generated lockfile, not hand-edited.
    "package-lock.json",
  ]),

  {
    // Everything JS/TS-flavored is scoped to JS/TS files only, so it never reaches for a
    // TypeScript parser (or the "import" plugin) while linting a JSON file below.
    files: ["**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}"],
    extends: [
      nextCoreWebVitals,
      nextTypescript,
      typescriptEslint.configs.strictTypeChecked,
      typescriptEslint.configs.stylisticTypeChecked,
      unicorn.configs.recommended,
      sonarjs.configs.recommended,
      security.configs.recommended,
      eslintComments.recommended,
    ],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["*.config.mjs", "*.config.js"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { "unused-imports": unusedImports },
    rules: {
      // --- No suppression, no escape hatches -------------------------------------------
      "@eslint-community/eslint-comments/no-use": ["error", { allow: [] }],
      "@typescript-eslint/ban-ts-comment": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-non-null-assertion": "error",

      // --- One function, one job -------------------------------------------------------
      complexity: ["error", { max: 8 }],
      "max-depth": ["error", 2],
      "max-lines-per-function": [
        "error",
        { max: 40, skipBlankLines: true, skipComments: true, IIFEs: true },
      ],
      "max-params": ["error", 3],
      "max-lines": ["error", { max: 300, skipBlankLines: true, skipComments: true }],
      "max-nested-callbacks": ["error", 3],
      "no-else-return": ["error", { allowElseIf: false }],
      "no-lonely-if": "error",
      "no-nested-ternary": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",

      // --- DRY --------------------------------------------------------------------------
      "sonarjs/no-identical-functions": "error",
      "sonarjs/no-duplicate-string": ["error", { threshold: 3 }],
      "sonarjs/no-identical-expressions": "error",
      "sonarjs/no-collapsible-if": "error",
      "sonarjs/prefer-immediate-return": "error",
      "no-magic-numbers": [
        "error",
        { ignore: [0, 1, -1], ignoreArrayIndexes: true, enforceConst: true, detectObjects: false },
      ],

      // --- Naming, no abbreviations ------------------------------------------------------
      "unicorn/prevent-abbreviations": [
        "error",
        {
          checkFilenames: true,
          checkProperties: true,
          allowList: {
            id: true,
            Id: true,
            url: true,
            Url: true,
            uri: true,
            Uri: true,
            api: true,
            Api: true,
            http: true,
            Http: true,
            db: true,
            Db: true,
            io: true,
            Io: true,
            sql: true,
            Sql: true,
            ui: true,
            Ui: true,
            env: true,
            Env: true,
            props: true,
            Props: true,
            ref: true,
            Ref: true,
            args: true,
            Args: true,
            params: true,
            Params: true,
            // Third-party config shapes we don't control (Playwright's testDir/outputDir,
            // tsconfig-style rootDir/outDir): "dir" for "directory" is unambiguous.
            dir: true,
            Dir: true,
            // @typescript-eslint/no-unused-vars' own option name, not ours to rename.
            vars: true,
            Vars: true,
            // Vitest's own config option (unstubEnvs), not ours to rename.
            envs: true,
            Envs: true,
          },
        },
      ],
      "unicorn/filename-case": ["error", { cases: { kebabCase: true, camelCase: true } }],
      "@typescript-eslint/naming-convention": [
        "error",
        { selector: "default", format: ["camelCase"], leadingUnderscore: "allow" },
        { selector: "variable", format: ["camelCase", "UPPER_CASE", "PascalCase"] },
        // React components: function-component-definition requires a function
        // declaration, and a component name must be PascalCase for JSX/React tooling.
        { selector: "function", format: ["camelCase", "PascalCase"] },
        { selector: "typeLike", format: ["PascalCase"] },
        { selector: "enumMember", format: ["UPPER_CASE"] },
        {
          selector: "variable",
          types: ["boolean"],
          format: ["PascalCase"],
          prefix: ["is", "has", "can", "should", "will", "did"],
        },
        // API payload keys and generated types are exempt: they follow the wire contract.
        { selector: "objectLiteralProperty", format: null },
        { selector: "typeProperty", format: null },
      ],

      // --- Correctness ---------------------------------------------------------------------
      eqeqeq: ["error", "always"],
      "no-console": "error",
      "no-debugger": "error",
      "no-alert": "error",
      "no-var": "error",
      "prefer-const": "error",
      "no-param-reassign": ["error", { props: true }],
      "@typescript-eslint/return-await": ["error", "always"],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/explicit-function-return-type": [
        "error",
        { allowExpressions: true, allowTypedFunctionExpressions: true },
      ],
      "unused-imports/no-unused-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "unicorn/no-null": "off",
      "unicorn/prefer-top-level-await": "off",

      // --- Layering: dependencies point downward only -------------------------------------
      "import/no-cycle": ["error", { maxDepth: Number.POSITIVE_INFINITY }],
      "import/no-restricted-paths": [
        "error",
        {
          zones: [
            {
              target: "./src/modules/*/!(*.controller.ts)",
              from: "./src/modules/*/*.controller.ts",
              message: "Nothing may import a controller. Dependencies point downward only.",
            },
            {
              target: "./src/modules/*/*.controller.ts",
              from: "./src/modules/*/*.repository.ts",
              message: "A controller must not touch a repository. Go through the service layer.",
            },
            {
              target: "./src/modules/*/*.repository.ts",
              from: "./src/modules/*/*.service.ts",
              message: "A repository must not depend on a service. Invert the dependency.",
            },
            {
              target: "./src/modules/*/*.service.ts",
              from: "./src/shared/http/**",
              message:
                "A service must not know about HTTP. Keep request and response objects in the controller.",
            },
          ],
        },
      ],
    },
  },

  // Component discipline and accessibility, on top of Next's own react/jsx-a11y rules.
  {
    files: ["**/*.{tsx,jsx}"],
    rules: {
      "react/jsx-no-bind": ["error", { allowArrowFunctions: true }],
      "react/no-array-index-key": "error",
      "react/jsx-key": ["error", { checkFragmentShorthand: true }],
      "react/no-unstable-nested-components": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/self-closing-comp": "error",
      "react/function-component-definition": [
        "error",
        { namedComponents: "function-declaration", unnamedComponents: "arrow-function" },
      ],
      "react-hooks/exhaustive-deps": "error",

      "jsx-a11y/no-static-element-interactions": "error",
      "jsx-a11y/click-events-have-key-events": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/label-has-associated-control": ["error", { assert: "either", depth: 3 }],
      "jsx-a11y/no-autofocus": "error",
      "jsx-a11y/media-has-caption": "error",
      "jsx-a11y/control-has-associated-label": "error",
      "jsx-a11y/no-noninteractive-element-interactions": "error",

      "react/no-danger": "error",
      "react/jsx-no-target-blank": ["error", { allowReferrer: false }],
      "react/jsx-no-script-url": "error",

      "max-lines-per-function": ["error", { max: 120, skipBlankLines: true, skipComments: true }],
    },
  },

  {
    files: [
      "src/app/**/page.tsx",
      "src/app/**/layout.tsx",
      "src/app/**/route.ts",
      "src/middleware.ts",
    ],
    rules: { "no-console": "error" },
  },

  // Tests may be longer and may use magic numbers freely: readable expectations matter more.
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/tests/**"],
    rules: {
      "max-lines-per-function": "off",
      "max-lines": "off",
      "no-magic-numbers": "off",
      "sonarjs/no-duplicate-string": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
  {
    files: ["**/*.test.{tsx,ts}"],
    plugins: { "testing-library": testingLibrary },
    rules: {
      ...testingLibrary.configs["flat/react"].rules,
      "testing-library/prefer-explicit-assert": "error",
      "testing-library/prefer-user-event": "error",
      "testing-library/no-node-access": "error",
      "testing-library/no-container": "error",
      "testing-library/prefer-screen-queries": "error",
      "testing-library/await-async-queries": "error",
    },
  },

  // Playwright end-to-end specs live outside src/ and run in their own runtime.
  {
    files: ["e2e/**/*.ts"],
    rules: {
      "max-lines-per-function": "off",
      "no-magic-numbers": "off",
      "sonarjs/no-duplicate-string": "off",
    },
  },

  // Config files and scripts are entry points, not application code. They also aren't
  // part of the app's tsconfig program (see allowDefaultProject above), so the
  // type-aware `no-unsafe-*` rules have no real type info to work with here and would
  // just flag every third-party config import - turned off for this category only.
  {
    files: ["*.config.{ts,mjs,js}", "scripts/**"],
    rules: {
      "no-console": "off",
      "no-magic-numbers": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
    },
  },

  // JSON: Prettier formats it, this just catches structural mistakes (duplicate keys,
  // unsafe numeric values). package-lock.json is generated and excluded above.
  {
    files: ["**/*.json"],
    plugins: { json: jsonPlugin },
    language: "json/json",
    rules: {
      ...jsonPlugin.configs.recommended.rules,
    },
  },

  prettierConfig,
]);
