#!/usr/bin/env bash
# Record the existing debt in this repository, once, so the gates can ratchet against it
# instead of blocking on problems that were already here.
#
#   ./.claude/scripts/generate-baseline.sh [--mode ratchet|observe|strict]
#
# Run this once, by hand, when adopting the standard in an existing codebase.
#
# Re-running it after writing new violations would launder them into the baseline, so it
# refuses to overwrite an existing baseline. A human who genuinely wants to re-baseline
# deletes .claude/baseline/ first, deliberately.

set -uo pipefail

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
BASELINE_DIRECTORY="$PROJECT_ROOT/.claude/baseline"
ADOPTION_CONFIG="$PROJECT_ROOT/.claude/adoption.conf"
REQUESTED_MODE="ratchet"

while [ $# -gt 0 ]; do
  case "$1" in
    --mode) REQUESTED_MODE="${2:-ratchet}"; shift 2 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; exit 1 ;;
  esac
done

case "$REQUESTED_MODE" in
  strict | ratchet | observe) ;;
  *) printf 'Mode must be strict, ratchet, or observe.\n' >&2; exit 1 ;;
esac

if [ -d "$BASELINE_DIRECTORY" ]; then
  printf 'A baseline already exists at %s\n' "$BASELINE_DIRECTORY" >&2
  printf 'Refusing to overwrite it - regenerating would absorb any new violations into\n' >&2
  printf 'the accepted debt. To re-baseline deliberately, delete the directory first.\n' >&2
  exit 1
fi

mkdir -p "$BASELINE_DIRECTORY"
cd "$PROJECT_ROOT" || exit 1

printf 'Recording the current state of %s\n\n' "$PROJECT_ROOT"

lint_output=""
typecheck_output=""
test_output=""

# Node / TypeScript
if [ -x "./node_modules/.bin/eslint" ]; then
  printf '  running eslint over the repository (this can take a while)\n'
  lint_output="$(./node_modules/.bin/eslint . --format unix 2>&1 || true)"
fi

if [ -x "./node_modules/.bin/tsc" ] && [ -f "tsconfig.json" ]; then
  printf '  running tsc --noEmit\n'
  typecheck_output="$(./node_modules/.bin/tsc --noEmit 2>&1 || true)"
fi

# Python
if command -v ruff >/dev/null 2>&1 && [ -f "pyproject.toml" ]; then
  printf '  running ruff check\n'
  lint_output="${lint_output}"$'\n'"$(ruff check --output-format concise . 2>&1 || true)"
fi

if command -v mypy >/dev/null 2>&1 && [ -f "pyproject.toml" ]; then
  printf '  running mypy\n'
  typecheck_output="${typecheck_output}"$'\n'"$(mypy . 2>&1 || true)"
fi

# Tests
if [ -f "package.json" ] && grep -q '"test"' package.json; then
  printf '  running the test suite\n'
  test_output="$(npm run --silent test 2>&1 || true)"
elif command -v pytest >/dev/null 2>&1; then
  printf '  running pytest\n'
  test_output="$(pytest -q 2>&1 || true)"
fi

# Count and record
count_lines_with() {
  printf '%s' "$1" | grep -ciE "$2" || true
}

# Count the "path:line:column: message" lines - the same parse the per-file counter and the
# gate's ratchet use, so all three numbers stay consistent with each other.
LINT_ERROR_COUNT="$(count_lines_with "$lint_output" '^[^: ]+:[0-9]+:')"
TYPECHECK_ERROR_COUNT="$(count_lines_with "$typecheck_output" '(error TS|error:)')"
TEST_FAILURE_COUNT="$(
  printf '%s' "$test_output" | grep -oE '[0-9]+ (failed|failing)' | grep -oE '^[0-9]+' | head -n 1
)"
TEST_FAILURE_COUNT="${TEST_FAILURE_COUNT:-0}"

# Per-file lint counts, so a file you touch cannot get worse even if the total holds.
# eslint --format unix and ruff concise both emit "path:line:column: message".
printf '%s' "$lint_output" \
  | grep -oE '^[^: ]+:[0-9]+' \
  | cut -d: -f1 \
  | sed "s|^$PROJECT_ROOT/||" \
  | sort \
  | uniq -c \
  | awk '{ printf "%s\t%s\n", $1, $2 }' \
  >"$BASELINE_DIRECTORY/lint-by-file.txt"

BASELINE_REF="$(git rev-parse HEAD 2>/dev/null || printf 'none')"

cat >"$BASELINE_DIRECTORY/counts.conf" <<EOF
# Generated by .claude/scripts/generate-baseline.sh - do not hand-edit.
# These numbers are the accepted debt at adoption time. They may go down, never up.
BASELINE_REF="$BASELINE_REF"
BASELINE_CREATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
LINT_ERROR_COUNT=$LINT_ERROR_COUNT
TYPECHECK_ERROR_COUNT=$TYPECHECK_ERROR_COUNT
TEST_FAILURE_COUNT=$TEST_FAILURE_COUNT
EOF

printf '%s' "$lint_output" >"$BASELINE_DIRECTORY/lint-output.txt"
printf '%s' "$typecheck_output" >"$BASELINE_DIRECTORY/typecheck-output.txt"

if [ ! -f "$ADOPTION_CONFIG" ]; then
  cat >"$ADOPTION_CONFIG" <<EOF
# How hard the gates bite. See .claude/skills/legacy-adoption/SKILL.md
#
#   strict   the whole repository must pass
#   ratchet  files you touch must pass; repository-wide counts must not grow
#   observe  report only, never block
#
ADOPTION_MODE="$REQUESTED_MODE"
EOF
fi

cat <<SUMMARY

Baseline recorded.

  mode                  $REQUESTED_MODE
  commit                $BASELINE_REF
  lint problems         $LINT_ERROR_COUNT
  type errors           $TYPECHECK_ERROR_COUNT
  failing tests         $TEST_FAILURE_COUNT

From here:

  - Any file you touch must come out clean. No new problems, ever.
  - The repository-wide numbers above may fall. They may not rise.
  - Nothing in the existing code blocks you.

Commit .claude/baseline/ and .claude/adoption.conf so the whole team ratchets from the
same point. Move to ADOPTION_MODE="strict" once the counts reach zero.

SUMMARY
