// The single source of truth for error codes. The backend raises these; the frontend
// branches on them. Never branch on a message string - messages change, codes do not.
//
// Adding a code is additive and safe. Renaming or removing one is a breaking API change.

export const ErrorCode = {
  // 400 / 422 - the request is wrong
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_PARAMETER: "INVALID_PARAMETER",
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

  // 401 - authentication
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  MULTI_FACTOR_REQUIRED: "MULTI_FACTOR_REQUIRED",
  MULTI_FACTOR_INVALID: "MULTI_FACTOR_INVALID",

  // 403 - authorization
  PERMISSION_DENIED: "PERMISSION_DENIED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",

  // 404 / 409 - resource state
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RESOURCE_GONE: "RESOURCE_GONE",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  OPTIMISTIC_LOCK_FAILED: "OPTIMISTIC_LOCK_FAILED",

  // Field-level validation
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  EMAIL_INVALID: "EMAIL_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_FOUND_IN_BREACH: "PASSWORD_FOUND_IN_BREACH",
  FIELD_REQUIRED: "FIELD_REQUIRED",
  FIELD_TOO_LONG: "FIELD_TOO_LONG",
  FIELD_OUT_OF_RANGE: "FIELD_OUT_OF_RANGE",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",

  // 429 / 5xx
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_FAILED_ATTEMPTS: "TOO_MANY_FAILED_ATTEMPTS",
  UPSTREAM_UNAVAILABLE: "UPSTREAM_UNAVAILABLE",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Default HTTP status for each code. A handler may override it, but rarely should. */
export const ERROR_CODE_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 422,
  INVALID_PARAMETER: 422,
  MALFORMED_REQUEST: 400,
  UNSUPPORTED_MEDIA_TYPE: 415,
  PAYLOAD_TOO_LARGE: 413,

  AUTHENTICATION_REQUIRED: 401,
  INVALID_CREDENTIALS: 401,
  ACCESS_TOKEN_EXPIRED: 401,
  ACCESS_TOKEN_INVALID: 401,
  REFRESH_TOKEN_INVALID: 401,
  REFRESH_TOKEN_EXPIRED: 401,
  REFRESH_TOKEN_REUSED: 401,
  MULTI_FACTOR_REQUIRED: 401,
  MULTI_FACTOR_INVALID: 401,

  PERMISSION_DENIED: 403,
  ACCOUNT_LOCKED: 403,
  ACCOUNT_SUSPENDED: 403,
  ACCOUNT_NOT_VERIFIED: 403,
  PASSWORD_CHANGE_REQUIRED: 403,

  RESOURCE_NOT_FOUND: 404,
  RESOURCE_ALREADY_EXISTS: 409,
  RESOURCE_CONFLICT: 409,
  RESOURCE_GONE: 410,
  INVALID_STATE_TRANSITION: 409,
  OPTIMISTIC_LOCK_FAILED: 409,

  EMAIL_ALREADY_REGISTERED: 409,
  EMAIL_INVALID: 422,
  PASSWORD_TOO_SHORT: 422,
  PASSWORD_TOO_LONG: 422,
  PASSWORD_FOUND_IN_BREACH: 422,
  FIELD_REQUIRED: 422,
  FIELD_TOO_LONG: 422,
  FIELD_OUT_OF_RANGE: 422,
  UNKNOWN_FIELD: 422,

  RATE_LIMIT_EXCEEDED: 429,
  TOO_MANY_FAILED_ATTEMPTS: 429,
  UPSTREAM_UNAVAILABLE: 502,
  UPSTREAM_TIMEOUT: 504,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};
